import type { CarLogoMeta, BrandName } from "./types";

export const brands: Record<BrandName, CarLogoMeta> = {
  "abarth": { title: "Abarth", slug: "abarth", country: "Italy", region: "Italian", founded: 1949, hex: "CC0000" },
  "acura": { title: "Acura", slug: "acura", country: "Japan", region: "Japanese", founded: 1986, hex: "1A1A1A" },
  "alfa-romeo": { title: "Alfa Romeo", slug: "alfa-romeo", country: "Italy", region: "Italian", founded: 1910, hex: "CC0000" },
  "alpina": { title: "Alpina", slug: "alpina", country: "Germany", region: "German", founded: 1965, hex: "003087" },
  "alpine": { title: "Alpine", slug: "alpine", country: "France", region: "French", founded: 1955, hex: "003087" },
  "apollo": { title: "Apollo", slug: "apollo", country: "Germany", region: "German", founded: 2004, hex: "1A1A1A" },
  "arash": { title: "Arash", slug: "arash", country: "UK", region: "British", founded: 1999, hex: "1A1A1A" },
  "aston-martin": { title: "Aston Martin", slug: "aston-martin", country: "UK", region: "British", founded: 1913, hex: "004225" },
  "audi": { title: "Audi", slug: "audi", country: "Germany", region: "German", founded: 1909, hex: "1A1A1A" },
  "bentley": { title: "Bentley", slug: "bentley", country: "UK", region: "British", founded: 1919, hex: "1A5276" },
  "bmw": { title: "BMW", slug: "bmw", country: "Germany", region: "German", founded: 1916, hex: "0066B2" },
  "brabus": { title: "Brabus", slug: "brabus", country: "Germany", region: "German", founded: 1977, hex: "1A1A1A" },
  "bristol": { title: "Bristol", slug: "bristol", country: "UK", region: "British", founded: 1945, hex: "1A1A1A" },
  "bugatti": { title: "Bugatti", slug: "bugatti", country: "France", region: "French", founded: 1909, hex: "1B1F8A" },
  "buick": { title: "Buick", slug: "buick", country: "USA", region: "American", founded: 1903, hex: "1A1A1A" },
  "cadillac": { title: "Cadillac", slug: "cadillac", country: "USA", region: "American", founded: 1902, hex: "1A1A1A" },
  "caterham": { title: "Caterham", slug: "caterham", country: "UK", region: "British", founded: 1973, hex: "CC0000" },
  "chevrolet": { title: "Chevrolet", slug: "chevrolet", country: "USA", region: "American", founded: 1911, hex: "CC0000" },
  "chrysler": { title: "Chrysler", slug: "chrysler", country: "USA", region: "American", founded: 1925, hex: "003087" },
  "citroen": { title: "Citroën", slug: "citroen", country: "France", region: "French", founded: 1919, hex: "CC0000" },
  "cupra": { title: "Cupra", slug: "cupra", country: "Spain", region: "Spanish", founded: 2018, hex: "C4A862" },
  "dacia": { title: "Dacia", slug: "dacia", country: "Romania", region: "Other", founded: 1966, hex: "003087" },
  "dallara": { title: "Dallara", slug: "dallara", country: "Italy", region: "Italian", founded: 1972, hex: "1A1A1A" },
  "de-tomaso": { title: "De Tomaso", slug: "de-tomaso", country: "Italy", region: "Italian", founded: 1959, hex: "003087" },
  "dodge": { title: "Dodge", slug: "dodge", country: "USA", region: "American", founded: 1900, hex: "CC0000" },
  "drako": { title: "Drako", slug: "drako", country: "USA", region: "American", founded: 2013, hex: "1A1A1A" },
  "ferrari": { title: "Ferrari", slug: "ferrari", country: "Italy", region: "Italian", founded: 1939, hex: "CD212A" },
  "fiat": { title: "Fiat", slug: "fiat", country: "Italy", region: "Italian", founded: 1899, hex: "CC0000" },
  "fisker": { title: "Fisker", slug: "fisker", country: "USA", region: "American", founded: 2007, hex: "1A1A1A" },
  "ford": { title: "Ford", slug: "ford", country: "USA", region: "American", founded: 1903, hex: "003087" },
  "genesis": { title: "Genesis", slug: "genesis", country: "South Korea", region: "Korean", founded: 2015, hex: "1A1A1A" },
  "ginetta": { title: "Ginetta", slug: "ginetta", country: "UK", region: "British", founded: 1958, hex: "CC0000" },
  "gumpert": { title: "Gumpert", slug: "gumpert", country: "Germany", region: "German", founded: 2004, hex: "1A1A1A" },
  "hamann": { title: "Hamann", slug: "hamann", country: "Germany", region: "German", founded: 1986, hex: "1A1A1A" },
  "hennessey": { title: "Hennessey", slug: "hennessey", country: "USA", region: "American", founded: 1991, hex: "1A1A1A" },
  "hispano-suiza": { title: "Hispano Suiza", slug: "hispano-suiza", country: "Spain", region: "Spanish", founded: 1904, hex: "003087" },
  "honda": { title: "Honda", slug: "honda", country: "Japan", region: "Japanese", founded: 1948, hex: "CC0000" },
  "hyundai": { title: "Hyundai", slug: "hyundai", country: "South Korea", region: "Korean", founded: 1967, hex: "003087" },
  "infiniti": { title: "Infiniti", slug: "infiniti", country: "Japan", region: "Japanese", founded: 1989, hex: "1A1A1A" },
  "jaguar": { title: "Jaguar", slug: "jaguar", country: "UK", region: "British", founded: 1935, hex: "003F7C" },
  "jeep": { title: "Jeep", slug: "jeep", country: "USA", region: "American", founded: 1941, hex: "1A1A1A" },
  "karma": { title: "Karma", slug: "karma", country: "USA", region: "American", founded: 2014, hex: "1A1A1A" },
  "kia": { title: "Kia", slug: "kia", country: "South Korea", region: "Korean", founded: 1944, hex: "CC0000" },
  "koenigsegg": { title: "Koenigsegg", slug: "koenigsegg", country: "Sweden", region: "Swedish", founded: 1994, hex: "FFCC00" },
  "ktm": { title: "KTM", slug: "ktm", country: "Austria", region: "Other", founded: 1934, hex: "FF6600" },
  "lamborghini": { title: "Lamborghini", slug: "lamborghini", country: "Italy", region: "Italian", founded: 1963, hex: "D4AF37" },
  "lancia": { title: "Lancia", slug: "lancia", country: "Italy", region: "Italian", founded: 1906, hex: "003087" },
  "land-rover": { title: "Land Rover", slug: "land-rover", country: "UK", region: "British", founded: 1948, hex: "004A2F" },
  "lexus": { title: "Lexus", slug: "lexus", country: "Japan", region: "Japanese", founded: 1989, hex: "1A1A1A" },
  "lincoln": { title: "Lincoln", slug: "lincoln", country: "USA", region: "American", founded: 1917, hex: "1A1A1A" },
  "lotus": { title: "Lotus", slug: "lotus", country: "UK", region: "British", founded: 1948, hex: "005C3E" },
  "lucid": { title: "Lucid", slug: "lucid", country: "USA", region: "American", founded: 2007, hex: "1A1A1A" },
  "mansory": { title: "Mansory", slug: "mansory", country: "Germany", region: "German", founded: 1989, hex: "D4AF37" },
  "maserati": { title: "Maserati", slug: "maserati", country: "Italy", region: "Italian", founded: 1914, hex: "003087" },
  "maybach": { title: "Maybach", slug: "maybach", country: "Germany", region: "German", founded: 1909, hex: "1A1A1A" },
  "mazda": { title: "Mazda", slug: "mazda", country: "Japan", region: "Japanese", founded: 1920, hex: "1A1A1A" },
  "mclaren": { title: "McLaren", slug: "mclaren", country: "UK", region: "British", founded: 1963, hex: "FF8000" },
  "mercedes-amg": { title: "Mercedes-AMG", slug: "mercedes-amg", country: "Germany", region: "German", founded: 1967, hex: "1A1A1A" },
  "mini": { title: "MINI", slug: "mini", country: "UK", region: "British", founded: 2001, hex: "1A1A1A" },
  "mitsubishi": { title: "Mitsubishi", slug: "mitsubishi", country: "Japan", region: "Japanese", founded: 1970, hex: "CC0000" },
  "morgan": { title: "Morgan", slug: "morgan", country: "UK", region: "British", founded: 1909, hex: "1A1A1A" },
  "mosler": { title: "Mosler", slug: "mosler", country: "USA", region: "American", founded: 1985, hex: "003087" },
  "nio": { title: "NIO", slug: "nio", country: "China", region: "Other", founded: 2014, hex: "1A1A1A" },
  "nissan": { title: "Nissan", slug: "nissan", country: "Japan", region: "Japanese", founded: 1933, hex: "C3002F" },
  "noble": { title: "Noble", slug: "noble", country: "UK", region: "British", founded: 1999, hex: "CC0000" },
  "opel": { title: "Opel", slug: "opel", country: "Germany", region: "German", founded: 1862, hex: "FFCC00" },
  "pagani": { title: "Pagani", slug: "pagani", country: "Italy", region: "Italian", founded: 1992, hex: "1A1A1A" },
  "panoz": { title: "Panoz", slug: "panoz", country: "USA", region: "American", founded: 1989, hex: "003087" },
  "peugeot": { title: "Peugeot", slug: "peugeot", country: "France", region: "French", founded: 1882, hex: "1A1A1A" },
  "pininfarina": { title: "Pininfarina", slug: "pininfarina", country: "Italy", region: "Italian", founded: 1930, hex: "1A1A1A" },
  "polestar": { title: "Polestar", slug: "polestar", country: "Sweden", region: "Swedish", founded: 2017, hex: "1A1A1A" },
  "porsche": { title: "Porsche", slug: "porsche", country: "Germany", region: "German", founded: 1931, hex: "1A1A1A" },
  "radical": { title: "Radical", slug: "radical", country: "UK", region: "British", founded: 1997, hex: "CC0000" },
  "renault": { title: "Renault", slug: "renault", country: "France", region: "French", founded: 1899, hex: "FFCC00" },
  "rezvani": { title: "Rezvani", slug: "rezvani", country: "USA", region: "American", founded: 2014, hex: "1A1A1A" },
  "rimac": { title: "Rimac", slug: "rimac", country: "Croatia", region: "Other", founded: 2009, hex: "0033A0" },
  "rivian": { title: "Rivian", slug: "rivian", country: "USA", region: "American", founded: 2009, hex: "2C6E49" },
  "rolls-royce": { title: "Rolls-Royce", slug: "rolls-royce", country: "UK", region: "British", founded: 1904, hex: "1A1A1A" },
  "ruf": { title: "RUF", slug: "ruf", country: "Germany", region: "German", founded: 1939, hex: "1A1A1A" },
  "saab": { title: "Saab", slug: "saab", country: "Sweden", region: "Swedish", founded: 1945, hex: "003087" },
  "saleen": { title: "Saleen", slug: "saleen", country: "USA", region: "American", founded: 1983, hex: "1A1A1A" },
  "seat": { title: "SEAT", slug: "seat", country: "Spain", region: "Spanish", founded: 1950, hex: "CC0000" },
  "shelby": { title: "Shelby", slug: "shelby", country: "USA", region: "American", founded: 1962, hex: "8B0000" },
  "singer": { title: "Singer", slug: "singer", country: "UK", region: "British", founded: 2009, hex: "1A1A1A" },
  "skoda": { title: "Skoda", slug: "skoda", country: "Czech Republic", region: "Other", founded: 1895, hex: "4B7B35" },
  "spyker": { title: "Spyker", slug: "spyker", country: "Netherlands", region: "Other", founded: 1999, hex: "003087" },
  "ssc": { title: "SSC", slug: "ssc", country: "USA", region: "American", founded: 1998, hex: "1A1A1A" },
  "subaru": { title: "Subaru", slug: "subaru", country: "Japan", region: "Japanese", founded: 1953, hex: "003087" },
  "techart": { title: "TechArt", slug: "techart", country: "Germany", region: "German", founded: 1987, hex: "1A1A1A" },
  "tesla": { title: "Tesla", slug: "tesla", country: "USA", region: "American", founded: 2003, hex: "CC0000" },
  "toyota": { title: "Toyota", slug: "toyota", country: "Japan", region: "Japanese", founded: 1937, hex: "CC0000" },
  "tvr": { title: "TVR", slug: "tvr", country: "UK", region: "British", founded: 1947, hex: "8B0000" },
  "ultima": { title: "Ultima", slug: "ultima", country: "UK", region: "British", founded: 1992, hex: "1A1A1A" },
  "vector": { title: "Vector", slug: "vector", country: "USA", region: "American", founded: 1978, hex: "1A1A1A" },
  "venturi": { title: "Venturi", slug: "venturi", country: "France", region: "French", founded: 1984, hex: "1A1A1A" },
  "volkswagen": { title: "Volkswagen", slug: "volkswagen", country: "Germany", region: "German", founded: 1937, hex: "003087" },
  "volvo": { title: "Volvo", slug: "volvo", country: "Sweden", region: "Swedish", founded: 1927, hex: "003087" },
  "w-motors": { title: "W Motors", slug: "w-motors", country: "UAE", region: "Other", founded: 2012, hex: "1A1A1A" },
  "wiesmann": { title: "Wiesmann", slug: "wiesmann", country: "Germany", region: "German", founded: 1985, hex: "1A1A1A" },
  "zenvo": { title: "Zenvo", slug: "zenvo", country: "Denmark", region: "Other", founded: 2004, hex: "1A1A1A" },
};
