// Auto-generated by exotic-car-logos-updater — do not edit manually
import abarth from "./logos/abarth.png";
import acura from "./logos/acura.png";
import alfaRomeo from "./logos/alfa-romeo.png";
import alpina from "./logos/alpina.png";
import alpine from "./logos/alpine.png";
import apollo from "./logos/apollo.png";
import arash from "./logos/arash.png";
import astonMartin from "./logos/aston-martin.png";
import audi from "./logos/audi.png";
import bentley from "./logos/bentley.png";
import bmw from "./logos/bmw.png";
import brabus from "./logos/brabus.png";
import bristol from "./logos/bristol.png";
import bugatti from "./logos/bugatti.png";
import buick from "./logos/buick.png";
import cadillac from "./logos/cadillac.png";
import caterham from "./logos/caterham.png";
import chevrolet from "./logos/chevrolet.png";
import chrysler from "./logos/chrysler.png";
import citroen from "./logos/citroen.png";
import dacia from "./logos/dacia.png";
import deTomaso from "./logos/de-tomaso.png";
import dodge from "./logos/dodge.png";
import drako from "./logos/drako.png";
import ferrari from "./logos/ferrari.png";
import fiat from "./logos/fiat.png";
import fisker from "./logos/fisker.png";
import ford from "./logos/ford.png";
import genesis from "./logos/genesis.png";
import ginetta from "./logos/ginetta.png";
import gumpert from "./logos/gumpert.png";
import hennessey from "./logos/hennessey.png";
import hispanoSuiza from "./logos/hispano-suiza.png";
import honda from "./logos/honda.png";
import hyundai from "./logos/hyundai.png";
import infiniti from "./logos/infiniti.png";
import jaguar from "./logos/jaguar.png";
import jeep from "./logos/jeep.png";
import karma from "./logos/karma.png";
import kia from "./logos/kia.png";
import koenigsegg from "./logos/koenigsegg.png";
import ktm from "./logos/ktm.png";
import lamborghini from "./logos/lamborghini.png";
import lancia from "./logos/lancia.png";
import landRover from "./logos/land-rover.png";
import lexus from "./logos/lexus.png";
import lincoln from "./logos/lincoln.png";
import lotus from "./logos/lotus.png";
import lucid from "./logos/lucid.png";
import mansory from "./logos/mansory.png";
import maserati from "./logos/maserati.png";
import maybach from "./logos/maybach.png";
import mazda from "./logos/mazda.png";
import mclaren from "./logos/mclaren.png";
import mercedesAmg from "./logos/mercedes-amg.png";
import mini from "./logos/mini.png";
import mitsubishi from "./logos/mitsubishi.png";
import morgan from "./logos/morgan.png";
import mosler from "./logos/mosler.png";
import nio from "./logos/nio.png";
import nissan from "./logos/nissan.png";
import noble from "./logos/noble.png";
import opel from "./logos/opel.png";
import pagani from "./logos/pagani.png";
import panoz from "./logos/panoz.png";
import peugeot from "./logos/peugeot.png";
import pininfarina from "./logos/pininfarina.png";
import polestar from "./logos/polestar.png";
import porsche from "./logos/porsche.png";
import radical from "./logos/radical.png";
import renault from "./logos/renault.png";
import rezvani from "./logos/rezvani.png";
import rimac from "./logos/rimac.png";
import rivian from "./logos/rivian.png";
import rollsRoyce from "./logos/rolls-royce.png";
import ruf from "./logos/ruf.png";
import saab from "./logos/saab.png";
import saleen from "./logos/saleen.png";
import seat from "./logos/seat.png";
import singer from "./logos/singer.png";
import skoda from "./logos/skoda.png";
import spyker from "./logos/spyker.png";
import ssc from "./logos/ssc.png";
import subaru from "./logos/subaru.png";
import techart from "./logos/techart.png";
import tesla from "./logos/tesla.png";
import toyota from "./logos/toyota.png";
import tvr from "./logos/tvr.png";
import ultima from "./logos/ultima.png";
import vector from "./logos/vector.png";
import venturi from "./logos/venturi.png";
import volkswagen from "./logos/volkswagen.png";
import volvo from "./logos/volvo.png";
import wMotors from "./logos/w-motors.png";
import wiesmann from "./logos/wiesmann.png";
import zenvo from "./logos/zenvo.png";

export const logoAssets: Record<string, string> = {
  "abarth": abarth,
  "acura": acura,
  "alfa-romeo": alfaRomeo,
  "alpina": alpina,
  "alpine": alpine,
  "apollo": apollo,
  "arash": arash,
  "aston-martin": astonMartin,
  "audi": audi,
  "bentley": bentley,
  "bmw": bmw,
  "brabus": brabus,
  "bristol": bristol,
  "bugatti": bugatti,
  "buick": buick,
  "cadillac": cadillac,
  "caterham": caterham,
  "chevrolet": chevrolet,
  "chrysler": chrysler,
  "citroen": citroen,
  "dacia": dacia,
  "de-tomaso": deTomaso,
  "dodge": dodge,
  "drako": drako,
  "ferrari": ferrari,
  "fiat": fiat,
  "fisker": fisker,
  "ford": ford,
  "genesis": genesis,
  "ginetta": ginetta,
  "gumpert": gumpert,
  "hennessey": hennessey,
  "hispano-suiza": hispanoSuiza,
  "honda": honda,
  "hyundai": hyundai,
  "infiniti": infiniti,
  "jaguar": jaguar,
  "jeep": jeep,
  "karma": karma,
  "kia": kia,
  "koenigsegg": koenigsegg,
  "ktm": ktm,
  "lamborghini": lamborghini,
  "lancia": lancia,
  "land-rover": landRover,
  "lexus": lexus,
  "lincoln": lincoln,
  "lotus": lotus,
  "lucid": lucid,
  "mansory": mansory,
  "maserati": maserati,
  "maybach": maybach,
  "mazda": mazda,
  "mclaren": mclaren,
  "mercedes-amg": mercedesAmg,
  "mini": mini,
  "mitsubishi": mitsubishi,
  "morgan": morgan,
  "mosler": mosler,
  "nio": nio,
  "nissan": nissan,
  "noble": noble,
  "opel": opel,
  "pagani": pagani,
  "panoz": panoz,
  "peugeot": peugeot,
  "pininfarina": pininfarina,
  "polestar": polestar,
  "porsche": porsche,
  "radical": radical,
  "renault": renault,
  "rezvani": rezvani,
  "rimac": rimac,
  "rivian": rivian,
  "rolls-royce": rollsRoyce,
  "ruf": ruf,
  "saab": saab,
  "saleen": saleen,
  "seat": seat,
  "singer": singer,
  "skoda": skoda,
  "spyker": spyker,
  "ssc": ssc,
  "subaru": subaru,
  "techart": techart,
  "tesla": tesla,
  "toyota": toyota,
  "tvr": tvr,
  "ultima": ultima,
  "vector": vector,
  "venturi": venturi,
  "volkswagen": volkswagen,
  "volvo": volvo,
  "w-motors": wMotors,
  "wiesmann": wiesmann,
  "zenvo": zenvo,
};
