// Auto-generated by exotic-car-logos-updater — do not edit manually
import audi from "./logos/audi.png";
import bentley from "./logos/bentley.png";
import bmw from "./logos/bmw.png";
import cadillac from "./logos/cadillac.png";
import chrysler from "./logos/chrysler.png";
import dodge from "./logos/dodge.png";
import ferrari from "./logos/ferrari.png";
import ford from "./logos/ford.png";
import honda from "./logos/honda.png";
import hyundai from "./logos/hyundai.png";
import jaguar from "./logos/jaguar.png";
import jeep from "./logos/jeep.png";
import lamborghini from "./logos/lamborghini.png";
import maserati from "./logos/maserati.png";
import mazda from "./logos/mazda.png";
import porsche from "./logos/porsche.png";
import subaru from "./logos/subaru.png";
import tesla from "./logos/tesla.png";
import toyota from "./logos/toyota.png";

export const logoAssets: Record<string, string> = {
  "audi": audi,
  "bentley": bentley,
  "bmw": bmw,
  "cadillac": cadillac,
  "chrysler": chrysler,
  "dodge": dodge,
  "ferrari": ferrari,
  "ford": ford,
  "honda": honda,
  "hyundai": hyundai,
  "jaguar": jaguar,
  "jeep": jeep,
  "lamborghini": lamborghini,
  "maserati": maserati,
  "mazda": mazda,
  "porsche": porsche,
  "subaru": subaru,
  "tesla": tesla,
  "toyota": toyota,
};
